# clash_template.yml
port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info

# ä»£ç†èŠ‚ç‚¹åˆ—è¡¨
proxies:
  - { name: 'ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 01', type: trojan, server: 3cb57cb8.sched.sma-dk.ali-oss.cn, port: 12021, password: b9dbc076-6b5c-4eee-af2d-04ecc7d1254e, udp: true, sni: cdn.alibaba.com, skip-cert-verify: true }

# ä»£ç†ç»„
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - 'ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 01'
      - DIRECT

# è§„åˆ™
rules:
  - MATCH,Proxy